type Language {
  id: ID
  name: String
  description: String
  code: String
  image: String
}

type UserLanguage {
  language: Language
  level: LanguageLevel
}

type LanguageLevel {
  id: ID
  name: String
  description: String
}

extend type Query {
  languages(id: ID, limit: Int, offset: Int): [Language] @pagination
  languageLevels: [LanguageLevel]
}
