# type LegalPeopleSearch {
#   id: ID
#   firstname: String
#   lastname: String
#   image: String
# }

# input UserInput {
#   nome: String!
# }

# extends type Query {
#     getLegalPeopleSearch(id: ID!): LegalPeopleSearch
#     listLegalPeopleSearch(firstname: String!, lastname: String, filter: TableLegalPeopleSearchInput, limit: Int, nextToken: String): LegalPeopleSearchConnection
# }

# extends type Mutation {
#     createLegalPeopleSearch(firstname: String!, lastname: String): LegalPeopleSearch
#       @auth(name: "create-legal-people-search")
#     deleteLegalPeopleSearch(id: ID!): LegalPeopleSearch
#       @auth(name: "delete-legal-people-search")
#     updateLegalPeopleSearch(id: ID!, firstname: String, lastname: String): LegalPeopleSearch
#       @auth(name: "update-legal-people-search")
# }
