type Position {
  id: ID
  name: String
  description: String
}

extend type Query {
  positions(id: ID, limit: Int, offset: Int): [Position] @pagination
}

extend type Mutation {
  createPosition(name: String!, description: String): Position
    @auth(name: "create-position")
  deletePosition(id: ID!): Position @auth(name: "delete-position")
  updatePosition(
    id: ID!
    name: String
    description: String
    image: Upload
  ): Position @auth(name: "update-position")
}
