type Skill {
  id: ID
  name: String
  description: String
  image: String
}

extend type Query {
  skills(id: ID, limit: Int, offset: Int): [Skill] @pagination
}

extend type Mutation {
  createSkill(name: String!, description: String, image: Upload): Skill
    @auth(name: "create-skill")
  deleteSkill(id: ID!): Skill @auth(name: "delete-skill")
  updateSkill(id: ID, name: String, description: String, image: Upload): Skill
    @auth(name: "update-skill")

  #add or replace a user skill
  setUserSkill(skill: ID!, stars: Int!): UserSkill @auth

  #delete a user skill
  deleteUserSkill(skill: ID!): UserSkill @auth
}
